### ISSUE TITLE
ngspice GND aliasing causes shorts

### ISSUE THREAD

**Issue by noqsi** [noqsi/gnet-spice-noqsi#3]
Ngspice globally aliases GND to be node 0, the datum node. This causes problems with subcircuits:
1. It is perfectly reasonable to connect a subcircuit's GND to something other than node 0.
2. A subcircuit without a GND pin will have its internal ground unconnected in a printed circuit netlist, but connected to node 0 in ngspice. Thus, it may simulate fine but not work when constructed.

In my opinion, this is an ngspice misfeature, but it appears we'll have to live with it. Therefore, we should alias GND to something ngspice won't recognize. Only in subcircuits? Configurable?

**Comment by holvo** [comment]
Put
`set no_auto_gnd`
into spinit or .spiceinit to supppress automatic conversion of GND to 0. You then have to take care of adequate grounding yourself.

**Comment by noqsi** [comment]
Thanks. Since the issue occurs when ground connections are explicitly provided, there's no problem with "taking care of adequate grounding". For a pure simulation job with global ground, one need not `set no_auto_ground`. There is thus no need to fix this in spice-noqsi, and this issue may be closed.
